services:
  go_ecoflow_exporter:
    image: tess1o/go-ecoflow-exporter:latest
    container_name: go_ecoflow_exporter
    ports:
      - 2112:2112
    restart: unless-stopped
    environment:
      ECOFLOW_ACCESS_KEY: ${ECOFLOW_ACCESS_KEY}
      ECOFLOW_SECRET_KEY: ${ECOFLOW_SECRET_KEY}
      PROMETHEUS_ENABLED: ${PROMETHEUS_ENABLED}
      METRIC_PREFIX: ${METRIC_PREFIX}
      TIMESCALE_ENABLED: ${TIMESCALE_ENABLED}
      TIMESCALE_URL: ${TIMESCALE_URL}
      REDIS_ENABLED: ${REDIS_ENABLED}
      REDIS_URL: ${REDIS_URL}
      REDIS_DB: ${REDIS_DB}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}